table Dim_Geography
	lineageTag: 46173a67-3de7-4ec3-9fdc-e34264b0c60e

	column GeographyKey
		dataType: string
		sourceColumn: GeographyKey
		summarizeBy: none
		isHidden
	column Region
		dataType: string
		sourceColumn: Region
		summarizeBy: none
	column State
		dataType: string
		sourceColumn: State
		summarizeBy: none
	column City
		dataType: string
		sourceColumn: City
		summarizeBy: none

	partition Dim_Geography = m
		mode: import
		source =
let
    Source = Csv.Document(
        File.Contents("C:\Users\Radianch_Tech\Desktop\DA_project\Sales-Performance-Dashboard\data\model\Dim_Geography.csv"),
        [Delimiter = ",", Columns = 4, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
    ),
    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{"GeographyKey", type text}, {"Region", type text}, {"State", type text}, {"City", type text}})
in
    ChangedTypes
