table Dim_Date
	lineageTag: e10a1bd5-8dc0-4caf-a111-8c9da27db564
	dataCategory: Time

	annotation __PBI_DateTable = true

	column Date
		dataType: dateTime
		sourceColumn: Date
		summarizeBy: none
	column Year
		dataType: int64
		sourceColumn: Year
		summarizeBy: none
	column Month
		dataType: int64
		sourceColumn: Month
		summarizeBy: none
	column MonthName
		dataType: string
		sourceColumn: MonthName
		summarizeBy: none
	column Quarter
		dataType: int64
		sourceColumn: Quarter
		summarizeBy: none
	column QuarterLabel
		dataType: string
		sourceColumn: QuarterLabel
		summarizeBy: none
	column YearMonth
		dataType: string
		sourceColumn: YearMonth
		summarizeBy: none

	partition Dim_Date = m
		mode: import
		source =
let
    Source = Csv.Document(
        File.Contents("C:\Users\Radianch_Tech\Desktop\DA_project\Sales-Performance-Dashboard\data\model\Dim_Date.csv"),
        [Delimiter = ",", Columns = 7, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
    ),
    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{"Date", type date}, {"Year", Int64.Type}, {"Month", Int64.Type}, {"MonthName", type text}, {"Quarter", Int64.Type}, {"QuarterLabel", type text}, {"YearMonth", type text}})
in
    ChangedTypes
